name: voc_up
description: Showing how to use vocal_message package
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.5
  vocal_message: #^1.0.0+1
    path: ../
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
