name: vocal_message
description: send and receive vocal messages through azure blob
version: 1.0.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.11
  audioplayers: ^4.1.0 #^5.1.0 
  font_awesome_flutter: ^9.1.0
  permission_handler: ^10.0.0 #^8.1.6
  record: #5.0.0-beta.3 depends on record_web which depends on sdk >= 3
    git: 
      url: https://github.com/flutter-painter/record
      path: record
      ref: 24663365be67494dcd95cd4e3ccb4e62e56eff69
  flutter_vibrate: ^1.1.0
  lottie: ^1.2.1
  xml: ^6.2.2
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0 # only used for dates

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/dustbin.json
    - assets/dustbin_grey.json
  