name: vocal_message
description: record vocals, upload them on azure blob and download replies
version: 0.0.1+1
repository: https://github.com/weebi-com/vocal_message

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  external_path: ^1.0.3
  just_audio: ^0.9.31  #0.9.11
  audioplayers: ^4.1.0 #^5.1.0 
  font_awesome_flutter: ^10.1.0
  permission_handler: ^10.0.0 #^8.1.6
  record: ^5.0.1
#    git: 
#      url: https://github.com/flutter-painter/record
#      path: record
#      ref: 6776acc2098f4087767b5e73b996c9889e80cf90
    #path: ../record/record
  flutter_vibrate: ^1.1.0
  lottie: ^1.2.1
  xml: ^6.2.2
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1 # only used for dates

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0 